config_version = "1"

[[components]]
pkg = "rust-std"
target = "wasm32-unknown-unknown"

[[components]]
pkg = "rust-src"
target = "*"

[[components]]
pkg = "rust-analysis"
target = "x86_64-apple-darwin"

[[components]]
pkg = "rust-std"
target = "x86_64-unknown-linux-musl"

[[components]]
pkg = "rls-preview"
target = "x86_64-apple-darwin"

[[components]]
pkg = "cargo"
target = "x86_64-apple-darwin"

[[components]]
pkg = "clippy-preview"
target = "x86_64-apple-darwin"

[[components]]
pkg = "rust-docs"
target = "x86_64-apple-darwin"

[[components]]
pkg = "rust-std"
target = "x86_64-apple-darwin"

[[components]]
pkg = "rustc"
target = "x86_64-apple-darwin"

[[components]]
pkg = "rustfmt-preview"
target = "x86_64-apple-darwin"
